export const GET_HOME_DATA = "GET_HOME_DATA";
export const GET_HOME_DATA_SUCCESS = "GET_HOME_DATA_SUCCESS";
export const GET_HOME_DATA_FAILURE = "GET_HOME_DATA_FAILURE";

export const GET_POSTS_DATA = "GET_POSTS_DATA";
export const GET_POSTS_DATA_SUCCESS = "GET_POSTS_DATA_SUCCESS";
export const GET_POSTS_DATA_FAILURE = "GET_POSTS_DATA_FAILURE";

export const GET_POSTDETAILS_DATA = "GET_POSTDETAILS_DATA";
export const GET_POSTDETAILS_DATA_SUCCESS = "GET_POSTDETAILS_DATA_SUCCESS";
export const GET_POSTDETAILS_DATA_FAILURE = "GET_POSTDETAILS_DATA_FAILURE";